### ISSUE TITLE
Research on the AI model output shape

### ISSUE THREAD

**Issue by wise0704** [GDSC-UDE-22-23/project-pronunciation#1]
The AI is going to train and perform on the (input, output) tuple of
`(prompt text + audio to evaluate, list of accuracy scores 0~100%)`.

Research is required on:

1. What are the aspects of pronunciation that need to be evaluated?
2. How can the output be shaped so that the details of evaluation (exactly which parts of words were mispronounced, etc.) can be determined?

**Comment by aggarwalpiush** [comment]
Instead of text, we should use some original native audio samples for evaluation.

**Comment by wise0704** [comment]
> Instead of text, we should use some original native audio samples for evaluation.

No, native audio samples are needed for training the model, not as input.

The goal is to have a model where the user is given a text to read, and we receive the user's speech. So our model is meant to carry out these tasks:

(1) `text -> correct speech`
(2) `correct speech, user speech -> accuracy score`

which can be resolved into one function:

`text, user speech -> accuracy score`.

Also, the topic of this issue is about the output - how exactly we need the accuracy score in order to be able to achieve [our goals](https://github.com/GDSC-UDE-22-23/project-pronunciation#our-goals).

Discussion on the input shape should be done in #2.

**Comment by wise0704** [comment]
[Following the conclusion posted here](https://github.com/GDSC-UDE-23/project-pronunciation/issues/2#issuecomment-1293986972), the output of such model (may not necessarily need ML) will be the phonetic transcription. An additional enhancement could be to also output the certainty score along with each phonetic alphabet.

For example, when heard "cat", output could be
```
[
    ("k", 0.91),
    ("ӕ", 0.87),
    ("t", 0.93)
]
```
