### ISSUE TITLE
Research on the AI model input shape

### ISSUE THREAD

**Issue by wise0704** [GDSC-UDE-22-23/project-pronunciation#2]
The AI is going to train and perform on the (input, output) tuple of
`(prompt text + audio to evaluate, list of accuracy scores 0~100%)`.

Determine how to handle the input.

Research is required on:
1. how to format audio input for machine learning
2. how to break apart (preprocess) the audio such that the relevant information (needed in evaluating pronunciation) is properly fed into the model

_Note: point 2 may depend on the output shape (aspects of pronunciation)._

**Comment by aggarwalpiush** [comment]
Can't we use following?

https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html

**Comment by wise0704** [comment]
> Can't we use following?
> 
> https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html

Yes, we will be using the audio tools provided by whichever framework we decide to use (pytorch, tf, etc.).

The problem is, however, about how we can go about preprocessing the audio.
For example, we will need to split the audio into each word, or even each syllable, in order to evaluate them.

So, the result of this research should have a conclusion similar to below (from my limited research):

Given for example "cat in a box", when evaluating phonetics, we first need to convert it to the correct notation
`/kӕt/ /in/ /ə/ /boks/`
and then break it down to
`("kӕ", "ӕt", "in", "ə", "bo", "ok", "s")`.
Those could be the input audio for evaluating the phonetics.
Similar process needs to be done for other aspects of pronunciation (stress, intonation and fluency, etc.).

**Comment by wise0704** [comment]
Conclusion from today's meeting:

> Our model is going to be in the form similar to a speech recognition software, but with different goals and thus different outputs.
Typically, speech recognition software takes in the form of
`spoken audio -> output text matching as closely as possible to the spoken text`.
In this case, if the input audio has poor pronunciation of a certain word, the software will _try to find the closest matching known word_ (with or without the help of the context).

> Although it could be used to determine whether a word was pronounced in a comprehensible way
(close enough -> outputs correct word, incorrect -> different word guessed by software),
it cannot be used to determine how accurately it was pronounced, and furthermore, how exactly the word was mispronounced.

> The idea is to have a similar model, but have the output produce a **phonetic transcription** (e.g. in [IPA](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet) or in a similar detailed encoding) of the input audio. This would allow us to correctly and accurately analyse the user's pronunciation in detail.

So, we will simply have to look into speech to phonetic transcription technology and see how the input is being handled there.
